services:
  - type: web
    name: telegram-pdf-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MASTER_ID
        sync: false
      - key: MASTER_PASSWORD
        value: admin123
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: false
    disk:
      name: telegram-bot-disk
      mountPath: /tmp
      sizeGB: 1